Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
